config/routes.rb
Rails.application.routes.draw do
 
  resources :people 
  resources :enemies

  resources :grudges, only: [:index, :show] do
    resources :enemies, only: [:index, :new, :edit]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  belongs_to :grudge, optional: true 
  belongs_to :person


  def person_name
    person ? person.name : ""
  end

  def person_name=(p_name)
    self.person = Person.find_or_create_by(name: p_name)
  end

  validates :name, :reason, :threat_level, presence: true
  validates :threat_level, numericality: { greater_than: 0, less_than_or_equal_to: 10 }
end

app/models/grudge.rb
class Grudge < ApplicationRecord
    has_many :enemies

    def threat_level
        self.enemies.sum(:threat_level)
      end
    
      def number_of_enemies
        self.enemies.count
      end
end

app/models/person.rb
class Person < ApplicationRecord


    has_many :enemies, dependent: :nullify 
    before_validation :set_reason 
    accepts_nested_attributes_for :enemies, reject_if: proc{|attr| attr['name'].blank?}

    
    private

    def set_reason
      if self.reason.blank?
        self.reason = Faker::Superhero.power
      end
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
    before_action :set_enemy, only: [:show, :edit, :update, :destroy]
    before_action :set_grudge
  
    # get "/enemys"
    def index
      if @grudge
        @enemies = @grudge.enemies
      else
        @enemies = Enemy.all
      end
      render :index
    end
  
    def show
      render :show
    end
  
    # get "/enemys/new"
    def new
      @enemy = Enemy.new
      render :new
    end
  
    # post "/enemys"
    def create
      # @enemy = enemy.create(enemy_params)
      #   if @enemy.valid?
      @enemy = Enemy.new(enemy_params)
        if @enemy.save
          redirect_to @enemy
        else
          render :new
        end
    end
  
    # get "/enemys/:id/edit"
    def edit
      render :edit
    end
  
    def update
      if @enemy.update(enemy_params)
        redirect_to @enemy
      else
        render :edit
      end
    end
  
    def destroy
      @enemy.destroy
      # add something here
      redirect_to enemys_path
    end
  
    private
  
    def set_enemy
      @enemy = Enemy.find_by(params[:id])
    end
  
    def set_grudge
      @grudge = Grudge.find_by(params[:grudge_id])
    end
  
    def enemy_params
      params.require(:enemy).permit(:name, :reason, :person_name, :threat_level, :grudge_id)
    end
  
  end

app/controllers/grudges_controller.rb
class GrudgesController < ApplicationController
    def index
    @grudges = Grudge.all
  end

  def show 
   @grudge = Grudge.find(params[:id])
  end
end

app/controllers/people_controller.rb
      class PeopleController < ApplicationController
        
        before_action :set_person, only: [:show, :destroy]
      
        def index
          @people = Person.all
        end
      
        def show
        end
      
        def new
          @person = Person.new
          2.times{ @person.enemies.build }
        end
      
        def create
          @person = Person.new(person_params)
          if @person.save
            redirect_to people_path
          else
            3.times{ @person.enemies.build }
            render :new
          end
        end
      
        def destroy
          @person.destroy
          redirect_to people_path
        end
      
        private
      
        def set_person
          @person = Person.find_by(params[:id])
        end
      
        def person_params
          params.require(:person).permit(:name, :reason, enemies_attributes: [:name, :reason, :threat_level, :grudge_id])
        end
      
      
end

app/helpers/application_helper.rb
module ApplicationHelper

    def pluralize(number_of_items, item)
        if number_of_items > 1
          "#{number_of_items} #{item.pluralize}"
        else
          "#{number_of_items} #{item}"
        end
      end
end

app/helpers/grudges_helper.rb
module GrudgesHelper

    def grudge(enemy)
        if enemy.grudge
          render partial: "grudges/grudge", locals: {grudge: enemy.grudge}
        else
          link_to "Edit #{enemy.name} to add a grudge!", edit_enemy_path(enemy)
        end
      end

end

app/helpers/persuns_helper.rb
module PersunsHelper
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/enemies/_form.html.erb
<%= form_for enemy do |f| %>
    <%= render partial: "layouts/errors", locals: {record: @enemy} %>
    <%= f.label :name %>
    <%= f.text_field :name %><br/>
    <%= f.label :reason %>
    <%= f.text_field :reason%><br/>
    <%= f.label :person_name %>
    <%= f.text_field :person_name %><br/>
  
    <% if false %>
    <input list="person_names" value=<%= enemy.person_name %> id="enemy[person_name]" name="enemy[person_name]" />
    <datalist id="person_names">
        <% Person.all.each do |person| %>
          <option value=<%= person.name %>>
        <% end %>
    </datalist>
    <% end %>
    <%= f.label :reason %>
    <%= f.text_field :reason %><br/>
    <% if grudge %>
      <%= f.hidden_field :grudge_id, value: grudge.id %>
    <% else %>
      <%= f.label :grudge%>
      <%= f.collection_select :grudge_id, Grudge.all, :id, :name, prompt: true %>
    <% end %>
    <%= f.submit %>
  <% end %>

app/views/enemies/edit.html.erb
<h1>Retcon <%= @enemy.name %></h1>
<%= render partial: "form", locals: {enemy: @enemy} %>

app/views/enemies/index.html.erb
<% if @grudge %>
<h1><%= render partial: "grudges/grudge", locals: {grudge: @grudge}%></h1>
<% else %>
<h1>WELCOME TO THE ENEMY REGISTRY</h1>
<% end %>

<h3>Current Roster</h3>
<ul><% @enemies.each do |enemy| %>
<li><%= link_to enemy.name, enemy %></li>
<% end %>
</ul>

<% if @grudge %>
<%= link_to "Add a new member of #{@grudge.name}", new_grudge_enemy_path(@grudge) %>
<% end %>

app/views/enemies/new.html.erb
<h3>GOT BEEF?</h3>
<% if @grudge %>
  <h1>  <%= @grudge.name %></h1>
<% else %>
  <h1> Youre a peaceful fellow </h1>
<% end %>
<%= render partial: "form", locals: {enemy: @enemy, grudge: @grudge} %>

app/views/enemies/show.html.erb
<h1><%= @enemy.name %></h1>
<p>Reason: <%= @enemy.reason %></p>
<p>Enemy: <%= @enemy.person_name %></p>
<p>Power Level: <%= "💪 " * @enemy.threat_level %></p>
<p>Grudge: <%= grudge(@enemy) %></p>

<%= button_to "Edit #{@enemy.name}", edit_enemy_path(@enemy), method: :get %>
<%= button_to "Delete #{@enemy.name}", @enemy, method: :delete %>

app/views/grudges/_grudge.html.erb
<div class="card">
<h3><%= link_to grudge.name, grudge_enemies_path(grudge) %></h3>
<p>Number of members: <%= grudge.number_of_enemies %></p>
<p>Total threat level: <%= grudge.threat_level %></p>
</div>

app/views/grudges/index.html.erb
<h1> Grudges!</h1>

<div class="cards">
  <%= render @grudges %>
</div>

app/views/grudges/show.html.erb
<div class="cards">
  <%= render @grudge %>
</div>

app/views/layouts/_errors.html.erb
<% if record.errors.any? %>
<p><%= "#{pluralize(record.errors.count, "error")} prevented this item from being saved:" %></p>
<ul><% record.errors.each do |error| %>
  <li><%= error.full_message %></li>
<% end %>
</ul>
<% end %>

app/views/layouts/_nav.html.erb
<br>
<%= link_to " Grudges", grudges_path %> |
<%= link_to "Enemies", enemies_path %> |
<%= link_to "New Enemy ", new_enemy_path %>|
<%= link_to "People", people_path %> |
<%= link_to "Add Person", new_person_path %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GrudgeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/nav" %>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<h1>Peeps</h1>
<ul><% @people.each do |person| %>
  <li><%= link_to person.name, person %></li>
  <% end %>
</ul>

app/views/people/new.html.erb
<h1>Log a new Person</h1>

<%= form_for @person do |f| %>
   <%= render partial: "layouts/errors", locals: {record: @person} %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :reason %>
  <%= f.text_field :reason %>
  <h2>Enemies</h2>
  <%= f.fields_for :enemies do |e| %>
    <p>Enemy:</p>
      <%= e.label :name %>
      <%= e.text_field :name %><br/>
      <%= e.label :reason %>
      <%= e.text_field :reason %><br/>
      <%= e.label :threat_level %>
      <%= e.number_field :threat_level, in: 1..10 %><br/>
      <%= e.label :grudge %>
      <%= e.collection_select :grudge_id, Grudge.all, :id, :name, prompt: true %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<h3>Reason for Grudge: <%= @person.reason%></h3>
<p>Adversaries: </p>
<% if @person.enemies.any? %>
  <ul>
    <% @person.enemies.each do |enemy| %>
    <li><%= link_to enemy.name, enemy %></li>
    <% end %>
  </ul>
<% else %>
  <ul><li><%= @person.name %> has no adversaries yet!</li></ul>
<% end %>
<%= button_to "Edit #{@person.name}", edit_person_path(@person), method: :get %>
<%= button_to "Kill #{@person.name}", @person, method: :delete, data: {
  confirm: "Are yousure you want to delete?" } %>